### ISSUE TITLE
Citation needed

### ISSUE THREAD

**Issue by zykadelic** [dutt/fler_kvinnliga_kodare#3]
There are many statements that lack citation that could really benefit from it. E.g. “Bolag med jämnställd styrelse presterar konsekvent bättre” and “Jämställda team är mer effektiva”.

**Comment by dutt** [comment]
Ska fixa vid tillfälle, har inte hunnit, har du trovärdiga källor bidra gärna. Eller bara en PR med citation needed på massor av ställen så man kan börja bocka av.

**Comment by dutt** [comment]
Har fixat källor till de två du nämnde och lite andra. Vill du öppna frågan igen skicka gärna en PR med specifikt vilka.

**Comment by zykadelic** [comment]
:+1:
